GET http://localhost:5000/peliculas

###

GET http://localhost:5000/peliculas/5fcd9c61929a3b1dfc6b72ba

###

POST http://localhost:5000/peliculas
Content-Type: application/json

{
    "titulo": "El padrino",
    "año": "2002-12-09",
    "puntaje": 9,
    "duracion": "123",
    "genero": "DRAMA",
    "descripcion": "buenarda",
    "imagen_link": "http://tuvieja.com"
}

###

DELETE http://localhost:5000/peliculas/5fcd9c61929a3b1dfc6b72ba

###

PATCH http://localhost:5000/peliculas/5fcd9c61929a3b1dfc6b72ba
Content-Type: application/json

{
    "titulo": "El padrino II"
}
